[tools]
selene = { source = "Roblox/Kampfkarren-selene", version = "0.21.0" }
stylua = { source = "Roblox/JohnnyMorganz-StyLua", version = "0.18.1" }
rojo = { source = "Roblox/rojo-rbx-rojo", version = "6.2.0" }
rotrieve = { source = "roblox/rotriever", version = "0.5.0-rc.4" }
