[tools]
selene = { source = "Kampfkarren/selene", version = "0.21.0" }
stylua = { source = "JohnnyMorganz/StyLua", version = "0.10.1" }
rojo = { source = "rojo-rbx/rojo", version = "6.2.0" }
rotrieve = { source = "roblox/rotriever", version = "0.5.0-rc.4" }
