[package]
name = "RegExp"
version = "0.1.3"
author = "Lua Foundation"
content_root = "src"
files = ["*", "!**/__tests__/**"]

[dev_dependencies]
JestGlobals = "github.com/roblox/jest-roblox@2.0.1"
TestEZ = "github.com/roblox/jest-roblox@2.0.1"
LuauPolyfill = "github.com/roblox/luau-polyfill@0.2.1"
