[package]
name = "RegExp"
version = "0.1.5"
author = "Lua Foundation"
content_root = "src"

[dev_dependencies]
JestRoblox = "github.com/roblox/jest-roblox@0.7.1"
LuauPolyfill = "github.com/roblox/luau-polyfill@0.1.5"
