[package]
name = "roblox/regexp"
description = "A regular expression library for Luau."
version = "0.2.2"
license = "MIT"
authors = ["Roblox <no-reply@roblox.com>"]

realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
repository = "https://github.com/Roblox/luau-regexp"

exclude = ["**/__tests__/**"]

[dependencies]
